/*
 * DialogWait.java
 *
 * Created on August 10, 2007, 11:38 AM
 */

package autotracker;

/**
 *
 * @author  jdoud
 */
public class DialogWait extends javax.swing.JDialog {
    
    /** Creates new form DialogWait */
    public DialogWait(java.awt.Frame parent, boolean modal) {
	super(parent, modal);
	initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        label = new javax.swing.JLabel();

        setTitle("Please wait");
        setAlwaysOnTop(true);
        setResizable(false);
        setUndecorated(true);
        label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/autotracker/wait24trans.gif")));
        label.setText("New Text");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label)
                .addContainerGap(219, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(46, 46, 46))
        );
        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    public void setText(String s) {
	label.setText(s);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
	java.awt.EventQueue.invokeLater(new Runnable() {
	    public void run() {
		new DialogWait(new javax.swing.JFrame(), true).setVisible(true);
	    }
	});
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel label;
    // End of variables declaration//GEN-END:variables
    
}
